---
######################################################################################
## Fichier de définition des objets de l'API d'exposition GEA
swagger: "2.0"
info:
  version: "0.4.0"
  title: API d'exposition GEA - Objets
  description: Fichier de définition des objets de l'API d'exposition GEA

######################################################################################
# Définition des objets
definitions:
  
  GEAResultatRecherche:
    type: object
    description: |
      Un objet représentant un résultat de recherche en GED.
      Il liste les métadonnées d'un document en GED.
    properties:
      idResultat:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAIdResultat"
      titre:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEATitre"
      dateCreation:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEADateCreation"
      dateModification:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEADateModification"
      version:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAVersion"
      idDocAia:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAIdDocAia"
      cleAia:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEACleAia"
      codeModele:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEACodeModele"
      type:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAType"
      sousType:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEASousType"
      siret:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEASiret"
      siren:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEASiren"
      idRc:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAIdRc"
      numContrat:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEANumContrat"
      natureContrat:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEANatureContrat"
      population:
         $ref: "./proprietes-v0.4.yaml#/definitions/GEAPopulationContrat"
      statutContrat:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAStatutContrat"
      organisme:  
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAOrganisme"
      dateEffet: 
        $ref: "./proprietes-v0.4.yaml#/definitions/GEADateEffet"
      dateValidite: 
        $ref: "./proprietes-v0.4.yaml#/definitions/GEADateValidite"
      docSigne:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEADocumentSigne"
      codeProduit:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEACodeProduit"
      libelleProduit:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEALibelleProduit"
      familleProduit:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAFamilleProduit"
      sousFamilleProduit:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEASousFamilleProduit"    
      typeProduit:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEATypeProduit"
      codeGIE:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEACodeGarantie"
      libelleGIE:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEALibelleGarantie"
      etat:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAEtat"
      pack:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAPack"
      option:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAOption"
      refDsn:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEARefDsn"
      moisDsn:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAMoisDsn"
      anneeDsn:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEAAnneeDsn"
      dateEdition:
        $ref: "./proprietes-v0.4.yaml#/definitions/GEADateEdition"
        
  GEAListeIdResultatRecherche:
     type: object
     description: Un objet représentant un tableau d'identifiants de résultat de recherche.
     properties:
      documents:
        type: array
        items:
          type: string
        minItems: 1
        maxItems: 500
        uniqueItems: true
     required: [documents]
     additionalProperties: false
        
######################################################################################
# Définition des services communs
paths: {}
