---
#######################################################################
## Fichier de définition des éléments de pagination
swagger: "2.0"
info:
  version: "0.1.0"
  title: API d'exposition GEA - Pagination
  description: Fichier de définition des éléments de pagination  

#######################################################################
# Définition des paramètres de pagination
parameters:

  MMPaginationIndex:
    in: query
    name: index
    type: integer
    format: int64
    minimum: 1
    description: Numéro de l'élément à afficher (1 = premier élément)
    
  MMPaginationLimite:
    in: query
    name: limite
    type: integer
    format: int64
    minimum: 1
    maximum: 500
    description: Nombre maximum d’éléments dans la page de résultat

#######################################################################
# Définition de l'objet de pagination
definitions:

  Pagination:
    type: object
    description: informations sur la page de résultats rendue
    required: [suivant]
    properties:
      suivant:
        type: boolean
        description: Existe-t-il ou non une page suivante
      precedent:
        type: boolean
        description: Existe-t-il ou non une page precedente
      total:
        type: integer
        format: int64
        description: nombre total d'éléments

#######################################################################
# Définition des services communs
paths: {}
