---
#####################################################################################
## Fichier de définition des paramètres de l'API d'exposition GEA
swagger: "2.0"
info:
  version: "0.4.0"
  title: API d'exposition GEA - Paramètres
  description: Fichier de définition des paramètres de l'API d'exposition GEA

#####################################################################################
# Définition des paramètres
parameters:
        
    GEAType:
      name: type
      description: Liste des codes entiers des types de documents en GED
      in: query
      required: false
      type: array
      items:
        type: integer
        format: int64
      minItems: 1
      uniqueItems: true
      
    GEASousType:
      name: sousType
      description: Liste des codes entiers des sous-types de documents en GED
      in: query
      required: false
      type: array
      items:
        type: integer
        format: int64
      minItems: 1
      uniqueItems: true
    
    GEASiret:
      name: siret
      description: Numéro SIRET
      in: query
      required: false
      type: string
      pattern: '^\d{14}$'
    
    GEAIdRc: 
      name: idRc
      description: Identifiant RC
      in: query
      required: false
      type: string
      minLength: 1
      
    GEAIdDocAia:
      name: idDocAia
      description: Identifiant AIA
      in: query
      required: false
      type: string
      minLength: 1
      
    GEACleAia:
      name: cleAia
      description: Clé AIA (identifiant unique AIA des cartes de tiers payant)
      in: query
      required: false
      type: string
      minLength: 1
    
    GEANumContrat:
      name: numContrat
      description: Numéro de contrat d'une pièce contractuelle
      in: query
      required: false
      type: string
      minLength: 1
    
    GEACodeProduit:
      name: codeProduit
      description: Code du produit
      in: query
      required: false
      type: string
      minLength: 1
    
    GEAEtat:
      name: etat
      description: Etat d'un modèle de pièce contractuelle
      in: query
      required: false
      type: string
      enum:
        - BROUILLON
        - RECETTE
        - VALIDE
        
    GEAReferenceDsn:
      name: refDsn
      description: Référence d'un document de type DSN
      in: query
      required: false
      type: string
      minLength: 1
        
    GEAIdResultatRecherche:
      name: idResultatRecherche
      description: |
        Identifiant unique d'un résultat du service de recherche.
        Il fait référence à un document en GED.
        Cet identifiant est utilisé par le service de récupération 
        de contenu afin d'identifier le document cible en GED.
      in: path
      required: true
      type: string
      minLength: 1

    GEAIndexContenu:
      name: indexContenu
      description: |
        Index entier du contenu à extraire d'un document en GED.
        Si aucun index de contenu n'est précisé alors le contenu primaire du document est retourné.
      in: query
      required: false
      type: integer
      format: int32
      minimum: 0
      default: 0
      
    GEAListeIdResultatRecherche:
      name: documents
      description: |
          Tableau des identifiants de résultat de recherche correspondant
          aux documents cibles
      in: body
      required: true
      schema:
        "$ref": "./objets-v0.4.yaml#/definitions/GEAListeIdResultatRecherche"

#######################################################################
# Définition des services communs
paths: {}
      