---
###########################################################################################
## Fichier de définition des propriétés de l'API d'exposition GEA
swagger: "2.0"
info:
  version: "0.4.0"
  title: API d'exposition GEA - Propriétés
  description: Fichier de définition des propriétés de l'API d'exposition GEA

###########################################################################################
# Définition des propriétés
definitions:

  GEAIdResultat:
    description: |
      Identifiant unique d'un résultat du service de recherche.
      Il fait référence à un document en GED.
      Cet identifiant est utilisé par le service de récupération de contenu 
      afin d'identifier le document cible en GED.
    type: string
    
  GEATitre:
    description: Titre du document en GED
    type: string
  
  GEADateCreation:
    description: Date de création du document en GED
    type: string
    format: date-time
    
  GEADateModification:
    description: Date de modification du document en GED
    type: string
    format: date-time
    
  GEAVersion:
    description: | 
      Libellé de la version du document en GED
      (format <Version Majeure>.<Version Mineure>).
    type: string
    pattern: '^\\d+\\.\\d+$'
  
  GEACodeModele:
    description: Code modèle du document 
    type: string
  
  GEAType:
      description: Type du document
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identifiant entier du type
        libelle:
          type: string
          description: Libellé du type
      required: [id, libelle]
      additionalProperties: false
  
  GEASousType:
      description: Sous-type du document
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Identifiant entier du sous-type
        libelle:
          type: string
          description: Libellé du sous-type
      required: [id, libelle]
      additionalProperties: false
  
  GEAIdDocAia:
      description: Identifiant AIA
      type: string
      
  GEACleAia:
      description: Clé AIA (Identifiant unique AIA d'une carte TP)
      type: string
  
  GEASiret:
      description: Numéro SIRET
      type: string
      pattern: '^\\d{14}$'
    
  GEASiren:
      description: Numéro SIREN
      type: string
      pattern: '^\\d{9}$'
  
  GEAIdRc: 
      description: Identifiant RC
      type: string
      minLength: 1
  
  GEARefDsn:
      description: Référence DSN du document
      type: string
  
  GEAMoisDsn:
      description: Mois de la DSN
      type: integer
      minimum: 1
      maximum: 12
      format: int32
  
  GEAAnneeDsn:
      description: Année de la DSN
      type: integer
      format: int32
  
  GEACodeProduit:
      description: Code du produit
      type: string
  
  GEALibelleProduit:
      description: Libellé du produit
      type: string
  
  GEATypeProduit:
      description: Type du produit
      type: string
      enum:
        - PREVOYANCE
        - SANTE
  
  GEAFamilleProduit:
      description: Famille du produit
      type: string
      enum:
        - COLLECTIF
        - INDIVIDUEL
      
  GEASousFamilleProduit:
      description: Sous-famille du produit
      type: string
      enum:
        - STANDARD
        - CCN  
  
  GEACodeGarantie:
      description: Code garantie
      type: string
  
  GEALibelleGarantie:
      description: Libellé de garantie
      type: string
  
  GEANumContrat:
      description: Numéro de contrat d'une pièce contractuelle
      type: string
  
  GEANatureContrat:
      description: Nature du contrat d'une pièce contractuelle
      type: string
  
  GEAPopulationContrat:
      description: Population concernée par le contrat
      type: string
      enum:
        - CADRE
        - NON CADRE
  
  GEAStatutContrat:
      description: Statut du contrat
      type: string
      
  GEAOrganisme:    
      description: Organisme assureur
      type: string
      
  GEADateEffet:
      description: Dates d'effet du contrat
      type: array
      items:
        type: string
        format: date-time
  
  GEADateValidite:    
      description: Date de validité du contrat
      type: string
      format: date-time
  
  GEADocumentSigne:
      description: Pièce contractuelle signée ?
      type: boolean
  
  GEAOption:
      description: Option
      type: string
  
  GEAPack:
      description: Pack
      type: string
  
  GEAEtat:
      description: Etat du modèle de pièce contractuelle
      type: string
      enum:
        - BROUILLON
        - RECETTE
        - VALIDE
      
  GEADateEdition:
      description: Date d'édition ou de numérisation
      type: string
      format: date-time
      
###########################################################################################
# Définition des services communs
paths: {}
  