---
#################################################################################################
## Fichier des définitions de sécurité de l'API d'exposition GEA
swagger: "2.0"
info:
  version: "0.1.0"
  title: API d'exposition documentaire GEA - Sécurité
  description: Fichier des définitions de sécurité de l'API d'exposition GEA
  
#################################################################################################
## Securité (à recopier dans chaque YAML)
schemes:
- https

# Sécurité BasicAuth
securityDefinitions:
  BasicAuth:
    type: basic

# Applique la sécurité BasicAuth à toutes les ressources
security:
  - BasicAuth: []

#################################################################################################
## Type MIME d'entrée/sortie

produces:
- application/json

#################################################################################################
# Définition des paramètres de sécurité
parameters:
  
  MMUserIdHeader:
    in: header
    name: MM-UserId
    type: string
    minLength: 1
    required: true
    description: >
      Identifiant du conseiller client qui réalise l'action,
      ou bien utilisateur applicatif banalisé
  
  MMAppIdHeader:
    in: header
    name: MM-AppId
    type: string
    minLength: 1
    description: >
      Identifiant de l'application consommatrice du service.
      Cet identifiant est valorisé par l'API GW en fonction de l'API Key

#################################################################################################
# Définition des services communs
paths: {}
