swagger: "2.0"
info:
  title:       Commun object
  description: Commun object
  version:     "1.0"

definitions:
  ResourceInformation:
    type: object
    properties:
      id:
        type: integer
        format: int64
