swagger: "2.0"
info:
  title:       Employee personal information
  description: API that exposes operations to add, retrieve and update employee personal information
  version:     "1.0"
schemes:
  - https
basePath: /v1

paths:
  /employees:
    post:
      summary: Add new employee personal information
      description: Add new employee personal information
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: personalInformation
          schema:
            $ref: '#/definitions/PersonalInformation'
      responses:
        200:
          description: OK
          schema:
            $ref: './common.yml#/definitions/ResourceInformation'
  /employees/{id}:
    get:
      summary: Retrieve employee personal information
      description: Retrieve employee personal information
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/PersonalInformation'
        404:
          description: User not found

definitions:
  PersonalInformation:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: The employee id
      firstname:
        type: string
        description: The employee firstname
      lastname:
        type: string
        description: The employee lastname
      mail:
        type: string
        description: The employee mail
      phonenumber:
        type: string
        description: The employee phone number
