swagger: "2.0"
info:
  title:       Employees profiles API
  description: API that exposes profiles of an employee
  version:     "1.0"
schemes:
  - https
basePath: /v1

paths:
  /profiles:
    get:
      summary: Returns a list of profiles.
      description: Returns a list of profiles.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Profiles'

definitions:
  Profiles:
    type: array
    items:
      $ref: '#/definitions/Profile'
  Profile:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: The profile id.
      name:
        type: string
        description: The profile name.