swagger: "2.0"
info:
  title:       Employees skills API
  description: API that exposes technical, functional and soft skills of an employee
  version:     1.0
schemes:
  - https
basePath: /v1

paths:
  /skills:
    get:
      summary: Returns a list of skills.
      description: Returns a list of skills.
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/Skills'

definitions:
  Skills:
    type: array
    items:
      $ref: '#/definitions/Skill'
  Skill:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: The skill id.
      name:
        type: string
        description: The skill name.